language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
script:
  - gem install xpath -v '2.0.0'
  - bundle install
  - rake db:migrate
  - rake db:test:load
before_install:
  - gem update --system
  - gem --version
