language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
script:
  - gem install debugger -v '1.6.1'
  - bundle install
  - rake db:migrate
  - rake db:test:load
  - bundle exec rspec ./spec/controllers/users_controller_spec.rb
before_install:
  #- gem update --system
  - gem --version
